title = "comma"

desc = ""

env="dev"

[server]
host = "127.0.0.1"

[db]
dns = "root:123456@tcp(127.0.0.1:3306)/comma?charset=utf8"

[es]
addr = "http://127.0.0.1:9200"
username = ""
password = ""
routers = [
	{ addr = "http://127.0.0.1:9200", index = "search_all", type = "all", filterType = 1, projectId = 0 },
	{ addr = "http://127.0.0.1:9200", index = "search_test", type = "all", filterType = 1, projectId = 0 },
]

[metric]
enable = true
job = "comma"
instance = ""
address = "127.0.0.1:9091"
intervalSync = 1